ARG PHP_VERSION=8.1
ARG PHP_TYPE=apache
FROM "php:$PHP_VERSION-$PHP_TYPE" AS base

RUN apt-get update && apt-get install -y --no-install-recommends libfreetype6 zlib1g-dev libjpeg-dev libpng-dev unzip git subversion

RUN docker-php-ext-install mysqli pdo pdo_mysql gd

# install node
ENV NVM_DIR="/home/user/.nvm" \
    NODE_VERSION="20.18.1" \
    NVM_VERSION="0.40.1"

RUN mkdir -p "$NVM_DIR" \
  && curl -o- "https://raw.githubusercontent.com/nvm-sh/nvm/v$NVM_VERSION/install.sh" | bash \
  && . $NVM_DIR/nvm.sh \
  && nvm install $NODE_VERSION \
  && nvm alias default $NODE_VERSION \
  && nvm use default

ENV NODE_PATH="$NVM_DIR/versions/node/v$NODE_VERSION/lib/node_modules"
ENV PATH="$NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH"

# install git lfs
RUN curl -sL -o git-lfs.tar.gz "$( \
    node -e "fetch('https://api.github.com/repos/git-lfs/git-lfs/releases/latest').then(r => r.json()).then(v => { \
        if (!v.assets || !v.assets.filter) { \
            console.log('unknown response:', JSON.stringify(v, null, 2)); \
        } \
        return v.assets.filter(i => /linux-amd64/.test(i.name)); \
    }).then(v => console.log(v[0].browser_download_url));" \
  )" \
  && ls \
  && tar xvf git-lfs.tar.gz \
  && cd git-lfs-* \
  && ./install.sh \
  && git lfs -v
