ARG PHP_VERSION=8.1
ARG PHP_TYPE=apache
FROM "php:$PHP_VERSION-$PHP_TYPE" AS base

RUN if (echo "$PHP_VERSION" | grep -Eq '^7\.2\.'); then  \
  sed -i 's/deb.debian.org/archive.debian.org/g' /etc/apt/sources.list \
  && sed -i 's/security.debian.org/archive.debian.org/g' /etc/apt/sources.list ; \
  fi

RUN apt-get update && apt-get install -y --no-install-recommends libfreetype6 zlib1g-dev libjpeg-dev libpng-dev unzip git subversion

RUN docker-php-ext-install mysqli pdo pdo_mysql gd

RUN curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash \
  && apt-get install git-lfs \
  && git lfs -v

# install node
ENV NVM_DIR="/home/user/.nvm" \
    NODE_VERSION="20.18.1" \
    NVM_VERSION="0.40.1"

RUN mkdir -p "$NVM_DIR" \
  && curl -o- "https://raw.githubusercontent.com/nvm-sh/nvm/v$NVM_VERSION/install.sh" | bash \
  && . $NVM_DIR/nvm.sh \
  && nvm install $NODE_VERSION \
  && nvm alias default $NODE_VERSION \
  && nvm use default

ENV NODE_PATH="$NVM_DIR/versions/node/v$NODE_VERSION/lib/node_modules"
ENV PATH="$NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH"
