#
# GitHub action executed when a PR is opened, asked for a review
# For debugging purposes, also when the assignment is modified.
#
# For now, runs only the UI tests.
#
# This action requires a secret called ARTIFACTS_PASS which is the key to upload on build-artifacts.
# This value can be found in the development keepass database.
#

name: Matomo for WordPress checkstyle Tests

on:
  pull_request:
    types: [ opened, review_requested, assigned, unassigned ]
  workflow_dispatch:

permissions:
  actions: read
  checks: none
  contents: read
  deployments: none
  issues: read
  packages: none
  pull-requests: read
  repository-projects: none
  security-events: none
  statuses: none

concurrency:
  group: php-${{ github.ref }}
  cancel-in-progress: true

env:
  PHP_VERSION: '8.0'
  HOST_RELEASE: 'ubuntu-20.04'

jobs:
  checkstyle:
    runs-on: ${{ env.HOST_RELEASE }}
    steps:
      - name: Checkout plugin project
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          path: wp-content/plugins/matomo

      - name: Setup PHP for checkstyle
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: curl, dom, exif, fileinfo, hash, imagick, json, mbstring, mysqli, openssl, pcre, sodium, xml, zip
          ini-values: |
            post_max_size=8M,
            memory_limit=256M,
            max_execution_time=30,
            always_populate_raw_post_data=-1,
            error_reporting=E_ALL,
            log_errors=on,
            display_errors=on,
            allow_url_fopen=on,
            zend.exception_ignore_args=Off
          tools: composer:v2
          coverage: none

      - name: Check PHP Version
        run: php -v

      - name: Install dependencies
        shell: bash
        run: cd ${{ github.workspace }}/wp-content/plugins/matomo && composer install

      - name: Run checkstyle
        shell: bash
        run: cd ${{ github.workspace }}/wp-content/plugins/matomo && ./vendor/bin/phpcs


